<template>
  <v-container>
		<v-layout column>
			<v-card>
			<v-card-title class="primary-title">
				<v-layout justify-center>
					<strong style="font-family: sanchez; font-size: 2.5em">Donate to Us!</strong>
				</v-layout>
			</v-card-title>
			<v-card-text>
        <v-container>
          <v-layout justify-center>
            <v-avatar size="300" tile><img src="../assets/Donate QR.jpg"></v-avatar>
          </v-layout>
        </v-container>
			</v-card-text>
		</v-card>
  </v-layout>
	</v-container>
</template>

<script>
export default {};
</script>